### ISSUE TITLE
Java.Lang.SecurityException getDataNetworkTypeForSubscriber (Android 11)

### ISSUE THREAD

**Issue by tchengck** [NAXAM/xam-mapbox-android#29]
Android API:
- compileSdkVersion 30
- targetSdkVersion 30

Hi guys,
to publish apps in Google Play Store from November 2021 onward we have to target the api level 30 for the targetSdkVersion. By doing this I am always getting the Java.Lang.SecurityException on Android 11 devices when the app is trying to access the map. Because of the exception the app will crash. Currently I have to ask the user for the READ_PHONE_STATE permission to solve this issue. But I don't really want to ask the user for this permission like before. To get the old behaviour without asking for permission we need Mapbox-Android-Telemetry-6.1.0: https://github.com/mapbox/mapbox-gl-native-android/issues/425 . They fix this issue there.
Is it possible to update the version of Mapbox-Android-Telemetry in this project?

<pre><code>  
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <1959115d56f8444789986cf39185638c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00063] in <1959115d56f8444789986cf39185638c>:0 
  at AndroidX.Fragment.App.Fragment.OnViewCreated (Android.Views.View view, Android.OS.Bundle savedInstanceState) [0x00049] in D:\a\1\s\generated\androidx.fragment.fragment\obj\Release\monoandroid90\generated\src\AndroidX.Fragment.App.Fragment.cs:2645 
  at Naxam.Controls.Mapbox.Platform.Droid.MapViewFragment.OnViewCreated (Android.Views.View view, Android.OS.Bundle savedInstanceState) [0x00001] in /Users/tcheng/Projekte/hiking-tips-app/src/Hu.Mountex.HikingTips/Naxam.Mapbox.Platform.Droid/MapViewFragment.cs:34 
  at AndroidX.Fragment.App.Fragment.n_OnViewCreated_Landroid_view_View_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_view, System.IntPtr native_savedInstanceState) [0x00018] in D:\a\1\s\generated\androidx.fragment.fragment\obj\Release\monoandroid90\generated\src\AndroidX.Fragment.App.Fragment.cs:2632 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.115(intptr,intptr,intptr,intptr)
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
	at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:150)
	at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
	at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
	at com.mapbox.mapboxsdk.maps.SupportMapFragment.onViewCreated(SupportMapFragment.java:112)
	at crc647daf67f241006816.MapViewFragment.n_onViewCreated(Native Method)
	at crc647daf67f241006816.MapViewFragment.onViewCreated(MapViewFragment.java:32)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)</code></pre>

**Comment by yero007** [comment]
I am also experiencing this issue.

**Comment by TimofeyBurak** [comment]
Same here. Is there a chance to get the fix before 1st November 2021, so the apps could be uploaded to Play Store?
More information here: https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by sonjz** [comment]
also stuck with this issue and needing api 30 for deploy.

**Comment by tuyen-vuduc** [comment]
Please check out latest version

https://www.nuget.org/packages/Com.Mapbox.Maps.Android
